apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
    index.html: |
      <html>
      <h1>Welcome to NGINX App</h1>
      </br>
      <h2>Hi! This is a configmap Index default contents before line based Kustomization </h2>
      </html